resources:
- name: lab-cluster
  properties:
    cluster:
      initialNodeCount: 2
      name: standard-cluster-1
      nodeConfig:
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
    zone: us-central1-a
  type: container.v1.cluster
